const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
// Use a classic script so opening index.html directly works without module CORS.
const bundle = ['courses.js', 'planner.js', 'hover.js', 'app.js'].map(file =>
  fs.readFileSync(path.join(root, file), 'utf8')
    .replace(/^import .*?;\r?\n/gm, '')
    .replace(/^export /gm, '')
).join('\n\n');
fs.writeFileSync(path.join(root, 'planner.bundle.js'), `// Generated by node scripts/build.cjs. Edit the source files instead.\n(() => {\n'use strict';\n${bundle}\n})();\n`);
console.log('Built planner.bundle.js');
